### Get all games
GET http://localhost:8080/games/


### Get Pokemon game details
GET http://localhost:8080/games/04a6af4b-f070-4755-8626-d182889f72b5/
Content-Type: application/json


### Create a new RPG game
POST http://localhost:8080/genres/7667b1d9-6377-43f9-8b92-e2eccd041b36/games/
Content-Type: application/json

{
  "name": "TestGame",
  "minimalPlayerAge": 69
}


### Update game
PUT http://localhost:8080/games/04a6af4b-f070-4755-8626-d182889f72b5/
Content-Type: application/json

{
  "name": "Pokemon v2",
  "minimalPlayerAge": 8
}


### Delete game
DELETE http://localhost:8080/games/34f4616e-90f0-49ce-87bf-95589aa1874a/

### Get all genres
GET http://localhost:8080/genres/

### Get a genre
GET http://localhost:8080/genres/7667b1d9-6377-43f9-8b92-e2eccd041b36/

### Create a new genre
POST http://localhost:8080/genres/
Content-Type: application/json

{
  "name": "TestGenre",
  "supportsMultiplayer": false
}

### Update a genre
PUT http://localhost:8080/genres/8f577562-032f-40d4-a5a2-ce91a9212bde/
Content-Type: application/json

{
  "name": "FPS Updated",
  "supportsMultiplayer": true
}


### Delete a genre
DELETE http://localhost:8080/genres/8f577562-032f-40d4-a5a2-ce91a9212bde/

